### ISSUE TITLE
Requirement Boilerplate

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/ionic-challenge#1]
# Objective
We want to learn how to use typescript, which is important for this challenge to build an Ionic app that uses Typescript Angular with a Facebook Integration.

# Task Implementation
- [x] Read up on Typescript's getting started guide.
- [x] Sign up for Ionic.
- [x] Read up on Angular's getting started guide
- [x] Import Ionic, Angular, and Typescript.
- [x] Get the template from Angular to run on my local server.
- [x] Populate the package.json with the necessary commands and dependencies.
- [x] Learn Cordova Ionic Integration.
- [x] Deploy the app to mobile.
