### ISSUE TITLE
User can login with Linkedin to see their own Face and Name

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/ionic-challenge#2]
# Overview
We are going to implement login integration with Linkedin. This will return to us a redirect that we can use to hopefully be able to show our profile information, such as our profile image and our name.

# Task Implementation
- [x] Read up on Linkedin's API for Delegated Login.
- [x] Be able to grab a token from the delegated login.
- [x] Be able to return a redirect URI from the delegated login if successful.
- [x] Be able to process a valid login token.
- [x] Be able to reject an invalid login token.
- [x] Be able to Grab the user's image.
- [x] Be able to handle the case where the user's image is not present.
- [x] Be able to grab the user's name.
- [x] Be able to handle if the user does not have a name.
