### ISSUE TITLE
Write up the Readme.

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/ionic-challenge#3]
# Objective
We want to detail the steps to replicate these processes in the readme.

# Task Implementation
- [x] Write up the readme with instructions as well as a gif that displays the final product to show people what it's supposed to look like when it is done.
- [x] Be able to replicate the instructions on a freshly cloned repository.
- [x] Reconfigure Proxies.
- [x] Create a Helper service to be able to bypass my free user limit.
- [x] Create a video demonstration.
- [x] Deploy to Heroku.
